$(document).ready(function(){
  $("#delivery").hide();
  $("#payment").hide();
  $(".submitbtn").hide();
  $(".show1").click(function(){
    $("#delivery").show(200);
    $(".show1").hide();
    $(".submitbtn").show(200);
    $("#payment").show(200);
    $("#row1").hide();
    $("#row2").hide();
    $("#row3").hide();
    $("#row4").hide();
    $("#row5").hide();
  });
});
